// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "dyvelt@tainosystems.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/usermanager/adminupdateuser": {
            "put": {
                "description": "Allows an admin yo edit a user's information",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "The user's info are edited",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/login": {
            "post": {
                "description": "Allows a registered user to login",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Login succeed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Login failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/logout": {
            "post": {
                "description": "End a session",
                "responses": {
                    "200": {
                        "description": "Logout succeed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/register": {
            "post": {
                "description": "Create a user",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "The firstname of the person",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Insert a new user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/updatepassword": {
            "put": {
                "description": "Update a user password",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Update a password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/updateuser": {
            "put": {
                "description": "Edit a user's informations",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Infos are edited",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/users": {
            "get": {
                "description": "Get all the users",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "List of all the users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.User": {
            "type": "object",
            "properties": {
                "createdOn": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastname": {
                    "type": "string"
                },
                "modifiedBy": {
                    "$ref": "#/definitions/sql.NullInt64"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "createdOn": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastname": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "sql.NullInt64": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.10.137:9090",
	BasePath:         "/api/usermanager",
	Schemes:          []string{},
	Title:            "USERMANAGER API",
	Description:      "This is a mini api that allows to perform basics CRUD operations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
