// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "dyvelt@tainosystems.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/usermanager/adminupdateuser": {
            "put": {
                "description": "Allows an admin yo edit a user's information",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "The user's info are edited",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/register": {
            "post": {
                "description": "Create a user",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Insert a new user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/updatepassword": {
            "put": {
                "description": "Create a user",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Update a password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/updateuser": {
            "put": {
                "description": "Edit a user's informations",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Infos are edited",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/usermanager/users": {
            "get": {
                "description": "Get all the users",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "List of all the users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.10.137:9090",
	BasePath:         "/api/usermanager",
	Schemes:          []string{},
	Title:            "USERMANAGER API",
	Description:      "This is a mini api that allows to perform basics CRUD operations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
